Downgrade sqlite3 from 2.0.2 to 1.7.3
Avoids this error:

LoadError: Error loading the 'sqlite3' Active Record adapter. Missing a
  gem it depends on? can't activate sqlite3 (~> 1.4), already activated
  sqlite3-2.0.2-x86_64-linux-gnu. Make sure all dependencies are added
  to Gemfile.

https://github.com/davidrunger/runger_actions/actions/runs/9485942404/job/26139103745?pr=560